### ISSUE TITLE
tflite2onnx error

### ISSUE THREAD

**Issue by HKLee2040** [kneron/ONNX_Convertor#12]
Follow the instruction:
https://github.com/kneron/ONNX_Convertor/tree/master/tflite-onnx#example-1-convert-model-to-the-onnx-optimized-for-kneron-toolchain

ONNX: onnx==1.4.1
Tensorflow: tensorflow==1.15.0
Python: 3.7.4

python ./onnx_tflite/tflite2onnx.py -tflite ./example/example.tflite -save_path ./example/example.onnx -release_mode True

It shows me the following error message:

-----------   information    ----------------
is_release_mode: True
model_path: /home/walker/work/kneron/ONNX_Convertor/tflite-onnx/example/example.tflite
model_save_path: /home/walker/work/kneron/ONNX_Convertor/tflite-onnx/example/example.onnx
-----------    start to generate  -----------
generating...
Error: Something Wrong
Model provided has model identifier 'ion ', should be 'TFL3'

------------   end   ------------------------

Is there any one who can help?

**Comment by ericwu155214** [comment]
Hi @HKLee2040,

I have experienced on this error message,
the example.tflite(LFS-tracked file) might not be downloaded successfully.

you can try `git lfs pull` to pull the lfs file.

**Comment by HKLee2040** [comment]
It works!  Thank you!
