### ISSUE TITLE
Questions about KL520 toolchain

### ISSUE THREAD

**Issue by JIANGJICHEN** [kneron/ONNX_Convertor#34]
Hello, I am following Kneron Linux Toolchain 520 Manual (v0.10.0) and have some questions. Hope someone can help me.

1. As FP-analysis requires some input images (input_image_folder "in input_params.json"), are there any special requirements for these images, such as image size, image content, number of images etc.?
2. How to choose the model id in “batch_input_params.json”? For example, I saw 1000 for MobileNet V2 and 19 for tiny-yolov3.
3. Does the Kneron toolchain or KL520 have a limit on model size? when I perform the _**3.5.2 Running the programs step**_ in “Toolchain 520 Manual” to generate the bin files for a yolo model (236 MB), I got an error “intput all_model_info file is larger than 29360128 bytes”.
4. I learned that Kneron toolchain offers compression. If the model is too large (as the problem in question 3), is the script called editor.py in the toolchain can help me? 

Thanks a lot!

**Comment by MrWhoami** [comment]
1. The images should be the input of the network. For example, for face recognition, we want face images. The image size doesn't matter. Our script will automatically resize it. The more image you feed to the analyzer, the more precise you get. However, the process will be slower.
2. For model id, if you would like to use your own model, just 1000 is okay. We also provide models. For those models, we have IDs for them.
3. This question I'm not quite sure. I'll ask someone who knows the details.
4. editor.py would not help you compress the model. Its purpose is to delete or add nodes in the onnx. We have a weight compression option for the compiler. But I don't think this will help that much.

**Comment by JIANGJICHEN** [comment]
Many thanks!
